/**
* Security
*/

Table user as U {
  id int [pk]
  username varchar [note: 'kolp'] 
  email varchar [note: 'a@a.com']
  fullname varchar [note: 'Markus Kolp']
  password_hash varchar [note: 'encrypted password']
  role_id int [ref: > R.id]
}

Table role as R {
  id int [pk]
  name roles 
}

Enum roles {
  Admin
  User
}

Table group as G {
  id int [pk]
  name varchar 
}

Table user_to_group as UG {
  user_id int [pk, ref: > U.id]
  group_id int [pk, ref: > G.id]
}

/**
* CRUD Application metadata
*/

Table application as APP {
  id int [pk]
  name varchar 
  alias varchar 
  spec_json varchar
  datasource_id int [ref: > DS.id]
}

Table application_to_group as APPTG {
  application_id int [pk, ref: > APP.id]
  group_id int [pk, ref: > G.id]
}


Table lookup as L {
  id int [pk]
  name varchar 
  sql_query varchar
  datasource_id int [ref: > DS.id]
}

Table datasource as DS {
  id int [pk]
  name varchar
  db_type db_types
  db_host varchar 
  db_port varchar 
  db_name varchar [note: 'database name']
  db_user varchar
  db_pass_hash varchar
}

Enum db_types {
  mssql
  postgres
  mysql
  oracle
  sqlite
}


/**
* External resources
*/

Table external_resource as ES {
  id int [pk]
  name varchar
  url varchar
  description varchar
  source varchar
  dataset varchar
}

Table external_resource_to_group as ESG {
  external_resource_id int [pk, ref: > ES.id]
  group_id int [pk, ref: > G.id]
}

/**
* Adhoc Tool
*/

Table adhoc as A {
  id int [pk]
  name varchar
  description varchar
  sql_query varchar
  order_by_default varchar
  output_format outputformats
  datasource_id int [ref: > DS.id]
}

Enum outputformats {
  HTML
  Excel
  CSV
}

Table adhoc_to_group as AG {
  adhoc_id int [pk, ref: > A.id]
  group_id int [pk, ref: > G.id]
}


/**
* custom sql
*/

Table customsql {
  id int [pk]
  alias varchar
  name varchar
  sql_query varchar
}

/**
* Others
*/

Table seq {
sequence_name varchar 
curval int
}

Table audit {
username varchar [ref: > U.username]
 t TIMESTAMP
 url varchar
 id varchar
 remark varchar
 request_method varchar
 request_body varchar
}



Table audit_adhoc [note: '''
  CREATE VIEW plainbi_audit_adhoc
as
select 
	coalesce(u.fullname, u.username) as user
	, a.t as datum
	, a.id as adhoc_id
	, pa.name as adhoc_name
	, case 
		when a.url like '%XLSX' then 'Excel'
		when a.url like '%CSV' then 'CSV'
		when a.url like '%HTML' then 'HTML'
		else 'HTML'		
	end as ausgabe_format
from plainbi_audit a, plainbi_user u, plainbi_adhoc pa 
where 1=1
and a.username = u.username
and a.id = pa.id
and url like '%/api/repo/adhoc/%/data%'
order by a.t desc
''', headercolor: #6724BB] {
 user varchar
 datum TIMESTAMP
 adhoc_id varchar
 adhoc_name varchar
 ausgabe_format varchar
}

Tablegroup views {
  audit_adhoc
}