[supervisord]
nodaemon=true         # Supervisor will run in the foreground

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"    # Nginx should not run as daemon
autostart=true
autorestart=false

[program:rest_server]
#command=python3 /opt/app/portal/backend/plainbi_backend.py -v
command=gunicorn -c /opt/app/portal/backend/gunicorn.conf.py "plainbi_backend.api:create_app()"
directory=/opt/app/portal/backend
autostart=true
autorestart=false
